Update jsrvctl

diff --git a/jsrvctl b/jsrvctl
--- a/jsrvctl
+++ b/jsrvctl
@@ -3,6 +3,7 @@
 instance_name="$2"
 oper="$1"
 source /etc/jsrvctl/jsrvctl.profile
+[ -z ${KILL_TIMEOUT} ] && export KILL_TIMEOUT=30
 
 check_user() {
     if [ -z "${ADMINGROUPS}" ]; then
@@ -22,37 +23,71 @@ check_user() {
 start_instance() {
     instance_name=$1
     if [ -f "/etc/jsrvctl/${instance_name}.profile" ]; then
-        . /etc/jsrvctl/${instance_name}.profile
+        source /etc/jsrvctl/${instance_name}.profile
     else
         echo "Error: '/etc/jsrvctl/${instance_name}.profile' file not found."
-        exit 4
+        exit 13
     fi
     if [ -z "${JAVA_OPTS}" ]; then
         echo "Error: Java environment variables is not properly set in '/etc/jsrvctl/${instance_name}.profile' file for this operation."
-        exit 5
+        exit 14
     fi
-    if [ -z "${APPUSER}" ]; then
-        echo "Error: APPUSER variable is not set in '/etc/jsrvctl/${instance_name}.profile' file for this operation."
-        exit 6
+    if [ -z $(id -u "${APPUSER}") ] >/dev/null 2>&1; then
+        echo "Error: APPUSER ${APPUSER} does not exist."
+        exit 15
     fi
     if [ $(ps -ef |grep java |grep -v grep |grep -v ant |grep "${PS_REGEX}" |wc -l) -ne 0 ]; then
         echo "'${instance_name}' is already started."
-        exit 7
+        exit 16
     fi
     echo "'${instance_name}' is being started..."
-    sudo -u ${APPUSER} -E instance_name="${instance_name}" bash -c '. /etc/jsrvctl/${instance_name}.profile; nohup "${STARTUP_CMD[@]}" >> /tmp/${instance_name}.log 2>> /tmp/${instance_name}.log &'
+    sudo -u ${APPUSER} -E instance_name="${instance_name}" bash -c 'source /etc/jsrvctl/${instance_name}.profile; nohup "${STARTUP_CMD[@]}" >> /tmp/${instance_name}.log 2>> /tmp/${instance_name}.log &'
     sleep 1
     echo "'${instance_name}' was started."
+    return 0
+}
+
+stop_instance() {
+    instance_name=$1
+    if [ -f "/etc/jsrvctl/${instance_name}.profile" ]; then
+        source /etc/jsrvctl/${instance_name}.profile
+    else
+        echo "Error: '/etc/jsrvctl/${instance_name}.profile' file not found."
+        exit 13
+    fi
+    if [ -z $(id -u "${APPUSER}") ] >/dev/null 2>&1; then
+        echo "Error: APPUSER ${APPUSER} does not exist."
+        exit 15
+    fi
+    echo "'${instance_name}' is being stopped..."
+    sudo -u ${APPUSER} -E instance_name="${instance_name}" bash -c 'source /etc/jsrvctl/${instance_name}.profile; nohup "${SHUTDOWN_CMD[@]}" >> /tmp/${instance_name}.log 2>> /tmp/${instance_name}.log &'
+    local i=0
+    while [ $(ps -ef |grep java |grep -v grep |grep -v ant |grep "${PS_REGEX}" |wc -l) -ne 0 ]
+    do
+        sleep 1
+        echo -n "$(ps -ef |grep java |grep -v grep |grep -v ant |grep "${PS_REGEX}" |wc -l)"
+        let i=${i}+1
+        if [[ ${i} -gt ${KILL_TIMEOUT} ]]; then
+            echo " Can not stop!, killing '${instance_name}'..."
+            local ipid=$(ps -ef |grep java |grep -v grep |grep -v ant |grep "${PS_REGEX}" |awk '{ print $2 }')
+            sudo -u ${APPUSER} -E ipid="${ipid}" bash -c 'kill -9 ${ipid} >> /tmp/${instance_name}.log 2>> /tmp/${instance_name}.log'
+        fi
+    done
+    echo "'${instance_name}' was stopped."
+    if [ -f /usr/local/bin/${instance_name}.clean ]; then
+        sudo -u ${APPUSER} -E instance_name="${instance_name}" bash -c '/usr/local/bin/${instance_name}.clean'
+        echo "'${instance_name}' Cache and Temp files deleted."
+    fi
     return 0
 }
 
 status_instance() {
     instance_name=$1
     if [ -f "/etc/jsrvctl/${instance_name}.profile" ]; then
-        . /etc/jsrvctl/${instance_name}.profile
+        source /etc/jsrvctl/${instance_name}.profile
     else
         echo "Error: '/etc/jsrvctl/${instance_name}.profile' file not found."
-        exit 4
+        exit 13
     fi
     if [ $(ps -ef |grep java |grep -v grep |grep -v ant |grep "${PS_REGEX}" |wc -l) -gt 0 ]; then
         echo "'${instance_name}' is running. Process count is $(ps -ef |grep java |grep -v grep |grep -v ant |grep "${PS_REGEX}" |wc -l)"
@@ -64,12 +99,24 @@ status_instance() {
 
 start() {
     if [[ "${instance_name}" == "all" ]]; then
-        for instance_name in $(cat /etc/jsrvctl/instances) 
+        for instance_name in $(cat /etc/jsrvctl/instances |grep -v '^[[:blank:]]*#' |grep -v '^[[:blank:]]*$') 
         do
             start_instance ${instance_name}
         done
     else
         start_instance ${instance_name} 
+    fi
+    return 0
+}
+
+stop() {
+    if [[ "${instance_name}" == "all" ]]; then
+        for instance_name in $(cat /etc/jsrvctl/instances |grep -v '^[[:blank:]]*#' |grep -v '^[[:blank:]]*$')
+        do
+            stop_instance ${instance_name}
+        done
+    else
+        stop_instance ${instance_name}
     fi
     return 0
 }
@@ -99,7 +146,7 @@ case "${oper}" in
         start
         ;;
     stop)
-        echo "stop"
+        stop
         ;;
     status)
         status
