Update jsrvctl

diff --git a/jsrvctl b/jsrvctl
--- a/jsrvctl
+++ b/jsrvctl
@@ -19,18 +19,57 @@ check_user() {
     return 0
 }
 
+start_instance() {
+    instance_name=$1
+    if [ -f "/etc/jsrvctl/${instance_name}.profile" ]; then
+        . /etc/jsrvctl/${instance_name}.profile
+    else
+        echo "Error: '/etc/jsrvctl/${instance_name}.profile' file not found."
+        exit 4
+    fi
+    if [ -z "${JAVA_OPTS}" ]; then
+        echo "Error: Java environment variables is not properly set in '/etc/jsrvctl/${instance_name}.profile' file for this operation."
+        exit 5
+    fi
+    if [ -z "${APPUSER}" ]; then
+        echo "Error: APPUSER variable is not set in '/etc/jsrvctl/${instance_name}.profile' file for this operation."
+        exit 6
+    fi
+    if [ $(ps -ef |grep java |grep -v grep |grep -v ant |grep "${PS_REGEX}" |wc -l) -ne 0 ]; then
+        echo "'${instance_name}' is already started."
+        exit 7
+    fi
+    echo "'${instance_name}' is being started..."
+    sudo -u ${APPUSER} -E instance_name="${instance_name}" bash -c '. /etc/jsrvctl/${instance_name}.profile; nohup "${STARTUP_CMD[@]}" >> /tmp/${instance_name}.log 2>> /tmp/${instance_name}.log &'
+    sleep 1
+    echo "'${instance_name}' was started."
+    return 0
+}
+
 status_instance() {
     instance_name=$1
     if [ -f "/etc/jsrvctl/${instance_name}.profile" ]; then
         . /etc/jsrvctl/${instance_name}.profile
     else
         echo "Error: '/etc/jsrvctl/${instance_name}.profile' file not found."
-        exit 13
+        exit 4
     fi
     if [ $(ps -ef |grep java |grep -v grep |grep -v ant |grep "${PS_REGEX}" |wc -l) -gt 0 ]; then
         echo "'${instance_name}' is running. Process count is $(ps -ef |grep java |grep -v grep |grep -v ant |grep "${PS_REGEX}" |wc -l)"
     else
         echo "'${instance_name}' is not running."
+    fi
+    return 0
+}
+
+start() {
+    if [[ "${instance_name}" == "all" ]]; then
+        for instance_name in $(cat /etc/jsrvctl/instances) 
+        do
+            start_instance ${instance_name}
+        done
+    else
+        start_instance ${instance_name} 
     fi
     return 0
 }
@@ -57,7 +96,7 @@ show_help() {
 check_user
 case "${oper}" in
     start)
-        echo "start"
+        start
         ;;
     stop)
         echo "stop"
