Update jsrvctl

diff --git a/jsrvctl b/jsrvctl
--- a/jsrvctl
+++ b/jsrvctl
@@ -12,17 +12,44 @@ check_user() {
         ADMINGROUPS=${ADMINGROUPS// /\\|}
         result=$(groups |grep -w ${ADMINGROUPS} |grep -v grep |wc -l)
         if [[ ${result} -eq  0 ]]; then
-            echo "Your username '($(whoami))' must belong to '${ADMINGROUPS}' group to use jsrvctl. Please contact your system administrator."
+            echo "Your username '($(whoami))' must belong to '${ADMINGROUPS}' group to use this script. Please contact your system administrator."
             exit 3
         fi
     fi
     return 0
 }
 
+status_instance() {
+    instance_name=$1
+    if [ -f "/etc/jsrvctl/${instance_name}.profile" ]; then
+        . /etc/jsrvctl/${instance_name}.profile
+    else
+        echo "Error: '/etc/jsrvctl/${instance_name}.profile' file not found."
+        exit 13
+    fi
+    if [ $(ps -ef |grep java |grep -v grep |grep -v ant |grep "${PS_REGEX}" |wc -l) -gt 0 ]; then
+        echo "'${instance_name}' is running. Process count is $(ps -ef |grep java |grep -v grep |grep -v ant |grep "${PS_REGEX}" |wc -l)"
+    else
+        echo "'${instance_name}' is not running."
+    fi
+    return 0
+}
+
+status() {
+    if [[ "${instance_name}" == "all" ]]; then
+        for instance_name in $(cat /etc/jsrvctl/instances |grep -v '^[[:blank:]]*#' |grep -v '^[[:blank:]]*$')
+        do
+            status_instance ${instance_name}
+        done
+    else
+        status_instance ${instance_name}
+    fi
+    return 0
+}
 
 show_help() {
 	echo "Usage: $0 {start|stop|status} {instance_name|all}"
-  echo "Help: $0 --help"
+        echo "Help: $0 --help"
 	exit 1 
 }
 
@@ -36,7 +63,7 @@ case "${oper}" in
         echo "stop"
         ;;
     status)
-        echo "status"
+        status
         ;;
     --help)
         show_help
